#!/bin/bash
validate() {
    password="${1}"
    isWeak=0
    # Verifica se a variável foi definida
    if [ -z "$password" ]; then
        error "A variável PASSWORD_ENV não foi definida."
        isWeak=1
    fi

    # Fazer as verificações de força da senha
    if [[ ${#password} -lt 15 ]]; then
        error "A senha deve ter pelo menos 15 caracteres."
        isWeak=1
    fi

    if [[ ! $password =~ [0-9] ]]; then
        error "A senha deve conter pelo menos um número."
        isWeak=1
    fi

    if ! [[ $password =~ [a-z] ]]; then
        error "A senha deve conter pelo menos uma letra minúscula."
        isWeak=1
    fi

    if ! [[ $password =~ [A-Z] ]]; then
        error "A senha deve conter pelo menos uma letra maiúscula."
        isWeak=1
    fi
    
    [[ $isWeak == 1 ]] && return 1
    return 0
}
generate() {
    openssl rand -base64 50
}
