version: '3'
 
services:
    server:
        build:
            context: ./alpine
            args:
                PERMIT_PASSWORD_LOGIN: "true"
        hostname: server
        ports:
            - "2222:22"
        environment:
            - MASTER_PASSWORD="Testee1234567%"
            - SSH_USERS=teste3:tesste1@asdasDr
            #- SSH_PUB_TESTE3=ssh-rsa ...